/**
 * RBAC 权限点定义（见 03-api.md §2.2）
 * 命名格式：<resource>:<action>
 */
export const RESOURCES = [
  'domain',
  'cache',
  'origin',
  'cert',
  'purge',
  'waf',
  'statistics',
  'log',
  'node',
  'vendor',
  'schedule',
  'user',
  'package',
  'order',
  'ticket',
  'notice',
  'site_config',
  'system_config',
  'audit',
  'report',
] as const

export const ACTIONS = [
  'create',
  'read',
  'update',
  'delete',
  'audit',
  'deploy',
  'export',
  'refund',
  'assign',
  'close',
] as const

export type Resource = (typeof RESOURCES)[number]
export type Action = (typeof ACTIONS)[number]
export type PermissionCode = `${Resource}:${Action}`

/** 权限点中文名 */
export const PERMISSION_NAME_MAP: Record<string, string> = {
  'domain:create': '创建域名',
  'domain:read': '查看域名',
  'domain:update': '更新域名',
  'domain:delete': '删除域名',
  'domain:audit': '审核域名',
  'cache:create': '创建缓存规则',
  'cache:read': '查看缓存规则',
  'cache:update': '更新缓存规则',
  'cache:delete': '删除缓存规则',
  'origin:create': '创建源站',
  'origin:read': '查看源站',
  'origin:update': '更新源站',
  'origin:delete': '删除源站',
  'cert:create': '上传证书',
  'cert:read': '查看证书',
  'cert:update': '更新证书',
  'cert:delete': '删除证书',
  'purge:create': '提交刷新',
  'purge:read': '查看刷新',
  'waf:create': '创建 WAF 规则',
  'waf:read': '查看 WAF 规则',
  'waf:update': '更新 WAF 规则',
  'waf:delete': '删除 WAF 规则',
  'statistics:read': '查看统计',
  'statistics:export': '导出统计',
  'log:read': '查看日志',
  'log:export': '导出日志',
  'node:create': '创建节点',
  'node:read': '查看节点',
  'node:update': '更新节点',
  'node:delete': '删除节点',
  'node:deploy': '部署节点',
  'vendor:create': '创建厂商',
  'vendor:read': '查看厂商',
  'vendor:update': '更新厂商',
  'vendor:delete': '删除厂商',
  'schedule:create': '创建调度策略',
  'schedule:read': '查看调度策略',
  'schedule:update': '更新调度策略',
  'schedule:delete': '删除调度策略',
  'user:create': '创建用户',
  'user:read': '查看用户',
  'user:update': '更新用户',
  'user:delete': '删除用户',
  'package:create': '创建套餐',
  'package:read': '查看套餐',
  'package:update': '更新套餐',
  'package:delete': '删除套餐',
  'order:read': '查看订单',
  'order:update': '更新订单',
  'order:refund': '订单退款',
  'ticket:read': '查看工单',
  'ticket:update': '更新工单',
  'ticket:assign': '分配工单',
  'ticket:close': '关闭工单',
  'notice:create': '创建公告',
  'notice:read': '查看公告',
  'notice:update': '更新公告',
  'notice:delete': '删除公告',
  'site_config:read': '查看网站配置',
  'site_config:update': '更新网站配置',
  'system_config:read': '查看系统配置',
  'system_config:update': '更新系统配置',
  'audit:read': '查看审计日志',
  'audit:export': '导出审计日志',
  'report:read': '查看报表',
  'report:export': '导出报表',
}

/**
 * 权限点全量清单
 */
export const PERMISSIONS: PermissionCode[] = [
  'domain:create',
  'domain:read',
  'domain:update',
  'domain:delete',
  'domain:audit',
  'cache:create',
  'cache:read',
  'cache:update',
  'cache:delete',
  'origin:create',
  'origin:read',
  'origin:update',
  'origin:delete',
  'cert:create',
  'cert:read',
  'cert:update',
  'cert:delete',
  'purge:create',
  'purge:read',
  'waf:create',
  'waf:read',
  'waf:update',
  'waf:delete',
  'statistics:read',
  'statistics:export',
  'log:read',
  'log:export',
  'node:create',
  'node:read',
  'node:update',
  'node:delete',
  'node:deploy',
  'vendor:create',
  'vendor:read',
  'vendor:update',
  'vendor:delete',
  'schedule:create',
  'schedule:read',
  'schedule:update',
  'schedule:delete',
  'user:create',
  'user:read',
  'user:update',
  'user:delete',
  'package:create',
  'package:read',
  'package:update',
  'package:delete',
  'order:read',
  'order:update',
  'order:refund',
  'ticket:read',
  'ticket:update',
  'ticket:assign',
  'ticket:close',
  'notice:create',
  'notice:read',
  'notice:update',
  'notice:delete',
  'site_config:read',
  'site_config:update',
  'system_config:read',
  'system_config:update',
  'audit:read',
  'audit:export',
  'report:read',
  'report:export',
]

/** 用户拥有的资源（用户端可操作自己的资源） */
export const USER_RESOURCES: Resource[] = [
  'domain',
  'cache',
  'origin',
  'cert',
  'purge',
  'waf',
  'statistics',
  'log',
]

/** 运维角色拥有的资源前缀（全部动作） */
export const OPS_RESOURCES: Resource[] = ['node', 'schedule']

/** 管理员被排除的权限点（见 03-api.md §2.3） */
export const ADMIN_EXCLUDED: PermissionCode[] = [
  'node:deploy',
  'system_config:update',
  'vendor:delete',
]

/** 运维额外拥有的只读权限点 */
export const OPS_EXTRA: PermissionCode[] = [
  'vendor:read',
  'statistics:read',
  'log:read',
]
